# File: .github/workflows/repo-sync.yml
name: 同步 Github Actions
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  # watch:
  #   types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lifeishard4me/Actions.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
